import {
  requirementGuidance,
  requirementInterpretationGuidance,
  requirements,
} from "@/lib/requirements";
import {
  architectureRecommendationGuidance,
  allRecommendationOptions,
  constraintGuidance,
  hostingRecommendationGuidance,
  modelRecommendationGuidance,
  recommendationSelectivityGuidance,
} from "@/lib/recommendations";
import { QuestionnaireSubmission } from "@/lib/schemas";

export function buildRecommendationPrompt(submission: QuestionnaireSubmission) {
  const requirementProfile = submission.answers.map((answer) => ({
    requirementId: answer.requirementId,
    theme: answer.theme,
    requirementName: answer.requirementName,
    question: answer.question,
    answerLabel: answer.answerLabel,
    score: answer.value,
    context: answer.context?.trim() || null,
  }));

  return [
    "You are a structured decision-support component for LLM system selection.",
    "Your task is to evaluate predefined model, architecture, and hosting options against a user requirement profile.",
    "",
    "Important constraints:",
    "1. Do not invent new recommendation options.",
    "2. Evaluate every predefined recommendation option exactly once.",
    "3. Use the exact layer, dimension, and option names from the recommendation options input.",
    "4. Return only valid JSON matching the required schema.",
    "",
    "Use both input types:",
    "1. The numerical score indicates the strength of the requirement.",
    "2. The optional context explains the use-case-specific reason behind the score.",
    "3. If context is missing, rely on the score and requirement definition only.",
    "",
    "Score discipline:",
    "1. Score 2 is a strong driver and can justify a strong recommendation.",
    "2. Score 1 is a mild supporting signal and should support conditionally_suitable or contribute to suitable only when combined with stronger signals.",
    "3. Score 0 is neutral or unknown and must not be used as a driver unless the user context explicitly supports it.",
    "4. Score -1 or -2 is low relevance and must not be used as a positive justification.",
    "",
    "Driver rules:",
    "1. Only describe a requirement as a strong driver if its score is 2.",
    "2. Do not describe a requirement as important, central, dominant, or prioritized if its score is 0 or negative.",
    "3. If a requirement has score 1, describe it only as a mild supporting signal.",
    "4. If a requirement has a negative score, it should reduce the relevance of options mainly serving that requirement.",
    "",
    "Classification labels:",
    "unsuitable = the option conflicts with important requirements and should generally not be selected.",
    "conditionally_suitable = the option can work, but only with safeguards, trade-offs, or specific conditions.",
    "suitable = the option fits important requirements and should be recommended.",
    "unaffected = the requirement profile does not strongly influence this option.",
    "",
    "Constraint rules:",
    "1. Constraint guidance indicates strong suitability signals. It does not automatically force a red label unless the user explicitly states that an option is prohibited or impossible.",
    "2. Use unsuitable only when there is a clear conflict with important requirements.",
    "3. If an option could still work with safeguards, classify it as conditionally_suitable instead of unsuitable.",
    "4. If requirements conflict, prefer conditionally_suitable and explain the trade-off.",
    "",
    "Governance rule:",
    "1. Do not mention governance, auditability, approved-tool policy, or compliance as a driver when governance score is 0 or negative.",
    "2. If privacy is high but governance is neutral, say the profile prioritizes privacy and data control, not governance.",
    "",
    "Verification rule:",
    "1. Do not mention output verification, traceability, citations, or audit checks as a driver when output verification score is 0 or negative.",
    "2. If reliability is high but output verification is neutral, explain that validation may support reliability, but do not claim verification was explicitly required.",
    "",
    "Replaceability rule:",
    "1. Do not mention vendor lock-in, provider switching, or model replacement as a driver unless replaceability has a positive score.",
    "2. If modularity is positive but replaceability is negative, say the system should be modular internally, but provider switching is not a major requirement.",
    "",
    "Planning rule:",
    "1. Do not mark planning and task decomposition as suitable solely because interactivity is high.",
    "2. Planning and task decomposition should be suitable only when multi-step work, task sequencing, agentic workflows, or complex task execution are clearly needed.",
    "3. If only interactivity is high, planning should usually be conditionally_suitable.",
    "",
    "Domain-specific model rule:",
    "1. Do not mark a domain-specific model as suitable unless domain specialization is explicitly required by the score profile or described in user context.",
    "2. If reliability is high but no domain is specified, mark domain-specific as conditionally_suitable rather than suitable.",
    "",
    "Task-specific model rule:",
    "1. Task-specific models are suitable when output format, reliability, repeatability, or a narrow task is strongly required.",
    "2. If the use case is broad, exploratory, or highly interactive, task-specific models should be conditionally_suitable rather than suitable.",
    "",
    "Tool and system access rule:",
    "1. If integration has a negative score, discourage tool and system access.",
    "2. Do not recommend API, MCP, database, CRM, ERP, or business-system integration when integration is negative unless user context explicitly requires it.",
    "3. Distinguish internal or private knowledge retrieval from business-system and tool integration. Negative integration discourages tool access, but does not automatically rule out private RAG.",
    "",
    "RAG rule:",
    "1. Knowledge retrieval or RAG should be suitable when internal knowledge, grounding, output verification, or source-based reliability is strongly needed.",
    "2. If output verification is neutral and no internal knowledge need is stated, RAG should usually be conditionally_suitable.",
    "3. If integration is negative, prefer private or self-contained retrieval over broad external tool or database integration.",
    "",
    "Hosting rule:",
    "1. Do not mark public cloud/API as unsuitable solely because privacy score is 1.",
    "2. Public cloud/API should be unsuitable only when privacy, deployment constraints, or context clearly indicate external processing is unacceptable.",
    "3. Do not mark private cloud, on-premise/local, or organization-controlled as suitable solely from weak privacy or governance signals.",
    "4. Edge or device-local should be suitable only when offline use, very low latency, device-local processing, or strict local processing is clearly needed.",
    "",
    "Model scale rule:",
    "1. Do not mark ultra-scale/frontier as suitable unless maximum reasoning quality, high-value complex reasoning, or advanced ideation is clearly required.",
    "2. Within scalability, prefer one primary suitable scale and use conditionally_suitable for adjacent alternatives.",
    "3. Do not mark all model scales as suitable.",
    "",
    "General weighting rules:",
    "1. High positive scores should influence the classification more strongly than low positive scores.",
    "2. A score of 0 should usually not strongly affect the recommendation.",
    "3. Do not mention exact calculations unless they are explicitly provided.",
    "4. If architecture flexibility is negative, do not claim the user wants broad future expansion with RAG, tools, validation, memory, and human review.",
    "5. If evidence is weak or mixed, prefer conditionally_suitable or unaffected over suitable or unsuitable.",
    "",
    "Table output rules:",
    "1. Do not provide row-level reasons for individual recommendation options.",
    "2. The traffic-light recommendation tables must contain only the fit classification for each option.",
    "",
    "Summary rules:",
    "1. The summary must be one concise paragraph of 80 to 120 words.",
    "2. It should state the main recommendation direction across model, architecture, and hosting.",
    "3. Mention only the strongest requirement drivers, meaning requirements with score 2.",
    "4. Mention score 1 requirements only if they help explain a trade-off.",
    "5. Do not mention requirements with score 0 or negative as drivers.",
    "6. Avoid listing every recommendation option.",
    "7. End with the most important trade-off or safeguard.",
    "",
    "Key explanation rules:",
    "1. Return 5 to 7 key explanations.",
    "2. Order key explanations by importance, from strongest decision driver to weaker supporting pattern.",
    "3. The first key explanation must correspond to the strongest score-2 requirement or strongest cluster of score-2 requirements.",
    "4. Each explanation should focus on one major pattern, not one option row.",
    "5. Each explanation should be 40 to 70 words.",
    "6. Use importance = high only for explanations based mainly on score-2 requirements.",
    "7. Use importance = medium for explanations based on mixed score-2 and score-1 signals.",
    "8. Use importance = low only for caveats, weak signals, or optional considerations.",
    "",
    "Reference integrity rules:",
    "1. Use only requirement IDs from the provided requirement definitions in relatedRequirements.",
    "2. Use only recommendation option names from the provided recommendation options in relatedOptions.",
    "3. Do not invent requirement IDs, option names, dimensions, or layers.",
    "",
    "Requirement profile:",
    JSON.stringify(requirementProfile, null, 2),
    "",
    "Requirement definitions:",
    JSON.stringify(
      requirements.map((requirement) => ({
        id: requirement.id,
        theme: requirement.theme,
        name: requirement.name,
        description: requirement.description,
        lowImportanceExample: requirement.lowImportanceExample ?? null,
        mediumImportanceExample: requirement.mediumImportanceExample ?? null,
        highImportanceExample: requirement.highImportanceExample ?? null,
      })),
      null,
      2,
    ),
    "",
    "Recommendation options:",
    JSON.stringify(allRecommendationOptions, null, 2),
    "",
    "Requirement importance guidance:",
    JSON.stringify(requirementGuidance, null, 2),
    "",
    "Requirement interpretation guidance:",
    JSON.stringify(requirementInterpretationGuidance, null, 2),
    "",
    "Recommendation relevance guidance:",
    JSON.stringify(
      {
        model: modelRecommendationGuidance,
        architecture: architectureRecommendationGuidance,
        hosting: hostingRecommendationGuidance,
      },
      null,
      2,
    ),
    "",
    "Constraint guidance:",
    JSON.stringify(constraintGuidance, null, 2),
    "",
    "Selectivity guidance:",
    JSON.stringify(recommendationSelectivityGuidance, null, 2),
  ].join("\n");
}

const recommendationItemJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: ["layer", "dimension", "option", "fit"],
  properties: {
    layer: {
      type: "string",
      enum: ["model", "architecture", "hosting"],
    },
    dimension: { type: "string" },
    option: { type: "string" },
    fit: {
      type: "string",
      enum: ["unsuitable", "conditionally_suitable", "suitable", "unaffected"],
    },
  },
} as const;

export const recommendationResponseJsonSchema = {
  name: "recommendation_result",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    required: [
      "summary",
      "modelRecommendations",
      "architectureRecommendations",
      "hostingRecommendations",
      "keyExplanations",
    ],
    properties: {
      summary: { type: "string" },
      modelRecommendations: {
        type: "array",
        items: recommendationItemJsonSchema,
      },
      architectureRecommendations: {
        type: "array",
        items: recommendationItemJsonSchema,
      },
      hostingRecommendations: {
        type: "array",
        items: recommendationItemJsonSchema,
      },
      keyExplanations: {
        type: "array",
        minItems: 5,
        maxItems: 7,
        items: {
          type: "object",
          additionalProperties: false,
          required: [
            "rank",
            "title",
            "explanation",
            "importance",
            "relatedRequirements",
            "relatedOptions",
          ],
          properties: {
            rank: { type: "number" },
            title: { type: "string" },
            explanation: { type: "string" },
            importance: {
              type: "string",
              enum: ["high", "medium", "low"],
            },
            relatedRequirements: {
              type: "array",
              items: { type: "string" },
            },
            relatedOptions: {
              type: "array",
              items: { type: "string" },
            },
          },
        },
      },
    },
  },
} as const;
